2022-09-18 01:02:35,346 Downloading and reading train artifact
wandb: ERROR Project nakany/exercise_14 does not contain artifact: "data_train.csv:latest"
Traceback (most recent call last):
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project nakany/exercise_14 does not contain artifact: "data_train.csv:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nakany/projects/cd0581-building-a-reproducible-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/random_forest/run.py", line 263, in <module>
    go(args)
  File "/Users/nakany/projects/cd0581-building-a-reproducible-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/random_forest/run.py", line 33, in go
    train_data_path = run.use_artifact(args.train_data).file()
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/nakany/miniforge3/envs/mlflow-a0f0eabde6cd07ea660111d983face3a47af906a/lib/python3.9/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project nakany/exercise_14 does not contain artifact: "data_train.csv:latest"
